/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/Ghost_Skull.gltf -o src/components/Ghost_Skull.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ghost(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Ghost_Skull.gltf')
  const { actions } = useAnimations(animations, group)

console.log(actions,'from Gost ');
  useEffect(() => {
    if (actions && actions["Flying_Idle"]) {
      actions["Flying_Idle"].reset().fadeIn(0.5).play();
  
      return () => {
        if (actions["Flying_Idle"]) {
          actions["Flying_Idle"].fadeOut(0.5);
        }
      };
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Ghost_Skull">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Ghost_Secondary} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Ghost_Main} skeleton={nodes.Cube001_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Ghost_Skull.gltf')
