/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/Wizard.gltf -o src/components/Wizard.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Wizard({hovered,...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Wizard.gltf')
  const { actions } = useAnimations(animations, group)

  console.log('wizzz',actions);
  useEffect(() => {
    console.log('iam here >>>>',hovered);
    const anim = hovered ? "Dance" : "Idle"
    if (actions && actions[anim]) {
      actions[anim].reset().fadeIn(0.5).play();
      

      return () => {
        if (actions[anim]) {
          actions[anim].fadeOut(0.5);
        }
      };
    }
  }, [hovered]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <group name="Wizard_Blob">
            <skinnedMesh name="Cube196" geometry={nodes.Cube196.geometry} material={materials.Wizard_Main} skeleton={nodes.Cube196.skeleton} />
            <skinnedMesh name="Cube196_1" geometry={nodes.Cube196_1.geometry} material={materials.Wizard_Secondary} skeleton={nodes.Cube196_1.skeleton} />
          </group>
          <group name="Wizard_Blob001">
            <skinnedMesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.Wizard_Main} skeleton={nodes.Cube000.skeleton} />
            <skinnedMesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.Wizard_Secondary} skeleton={nodes.Cube000_1.skeleton} />
            <skinnedMesh name="Cube000_2" geometry={nodes.Cube000_2.geometry} material={materials.Eye_Black} skeleton={nodes.Cube000_2.skeleton} />
            <skinnedMesh name="Cube000_3" geometry={nodes.Cube000_3.geometry} material={materials.Eye_White} skeleton={nodes.Cube000_3.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Wizard.gltf')
